import { GoogleGenAI, Type } from "@google/genai";

export interface Recipe {
  id: string;
  name: string;
  category: string;
  country: string;
  description: string;
  ingredients: string[];
  instructions: string[];
  prepTime: string;
  difficulty: "Oson" | "O'rta" | "Qiyin";
  calories: number;
  specialTouch: string;
}

export async function generateRecipe(prompt: string): Promise<Recipe | null> {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Menga quyidagi mavzuda bitta haqiqiy va an'anaviy retsept yaratib ber: ${prompt}. Hech qanday fantastik yoki kelajak elementlarini qo'shma. Taom realistik, tandirda yoki o'choqda pishiriladigan bo'lsin. Javob faqat JSON formatida bo'lsin. Davlatini ham ko'rsat (masalan: O'zbekiston, Yaponiya, Rossiya, Angliya va h.k.).`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            id: { type: Type.STRING },
            name: { type: Type.STRING },
            category: { type: Type.STRING },
            country: { type: Type.STRING },
            description: { type: Type.STRING },
            ingredients: { type: Type.ARRAY, items: { type: Type.STRING } },
            instructions: { type: Type.ARRAY, items: { type: Type.STRING } },
            prepTime: { type: Type.STRING },
            difficulty: { type: Type.STRING, enum: ["Oson", "O'rta", "Qiyin"] },
            calories: { type: Type.NUMBER },
            specialTouch: { type: Type.STRING },
          },
          required: ["id", "name", "category", "country", "description", "ingredients", "instructions", "prepTime", "difficulty", "calories", "specialTouch"],
        },
      },
    });

    if (!response.text) throw new Error("No response text");
    return JSON.parse(response.text);
  } catch (error) {
    console.error("Error generating recipe:", error);
    return null;
  }
}

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: "1",
    name: "Dum Sho'rva",
    category: "Sho'rva",
    country: "O'zbekiston",
    description: "Mol dumidan tayyorlangan, juda mazali va quvvatbaxsh an'anaviy sho'rva.",
    ingredients: ["Mol dumi", "Sabzi", "Piyoz", "Kartoshka", "Ziravorlar"],
    instructions: ["Dum bo'laklarini 2 soat davomida qaynatish", "Sabzavotlarni qo'shish", "Past olovda yana 30 daqiqa pishirish"],
    prepTime: "2.5 soat",
    difficulty: "O'rta",
    calories: 350,
    specialTouch: "Maxsus sopol qozonda pishirilgan, barcha vitaminlar saqlab qolingan."
  },
  {
    id: "2",
    name: "Sushi Roll 'Classic Tokyo'",
    category: "Dengiz taomlari",
    country: "Yaponiya",
    description: "Yangi baliq va sara guruchdan tayyorlangan, an'anaviy yapon sushisi.",
    ingredients: ["Sara guruch", "Tazja tuna", "Nori", "Yangi bodring"],
    instructions: ["Guruchni pishirish", "Baliqni yupqa kesish", "Roll shakliga keltirish"],
    prepTime: "30 daqiqa",
    difficulty: "Qiyin",
    calories: 280,
    specialTouch: "Sushi bo'laklari yangi tayyorlangan vasabi bilan tortiladi."
  },
  {
    id: "3",
    name: "Borsh 'An'anaviy'",
    category: "Sho'rva",
    country: "Rossiya",
    description: "Klassik usulda tayyorlangan, to'yimli va vitaminli borsh.",
    ingredients: ["Lavlagi", "Go'sht", "Karam", "Yangi smetana"],
    instructions: ["Sabzavotlarni bug'da pishirish", "Bulyon bilan aralashtirish"],
    prepTime: "20 daqiqa",
    difficulty: "Oson",
    calories: 190,
    specialTouch: "Yangi smetana borsh ta'mini yanada boyitadi."
  },
  {
    id: "4",
    name: "Fish & Chips 'London Style'",
    category: "Qovurilgan taomlar",
    country: "Angliya",
    description: "Tavada qovurilgan baliq va qarsildoq kartoshka.",
    ingredients: ["Oq baliq", "Kartoshka", "Oliy navli un", "Pivo xamiri"],
    instructions: ["Baliqni xamirga botirish", "Issiq yog'da qovurish"],
    prepTime: "15 daqiqa",
    difficulty: "O'rta",
    calories: 410,
    specialTouch: "Kartoshka bo'laklari an'anaviy usulda kesilgan."
  },
  {
    id: "5",
    name: "Mazzali Shokoladli Tort",
    category: "Desertlar",
    country: "Fransiya",
    description: "Haqiqiy shokolad va qaymoqdan tayyorlangan yumshoq desert.",
    ingredients: ["Shokolad", "Un", "Tuxum", "Qaymoq", "Shakar"],
    instructions: ["Biskvit pishirish", "Qaymoqli krem tayyorlash", "Shokolad bilan bezash"],
    prepTime: "40 daqiqa",
    difficulty: "O'rta",
    calories: 450,
    specialTouch: "Qo'lda tayyorlangan murakkab shokoladli naqshlar bilan bezatilgan."
  },
  {
    id: "6",
    name: "Ramen 'Kyoto Classic'",
    category: "Suyuq taomlar",
    country: "Yaponiya",
    description: "Tabiiy bulyon va pishirilgan tuxum bilan boyitilgan ramen.",
    ingredients: ["Ramen ugrasi", "Tabiiy bulyon", "Pishirilgan tuxum", "Yangi ko'katlar"],
    instructions: ["Ugrani pishirish", "Bulyonni isitish", "Tuxumni pishirish"],
    prepTime: "10 daqiqa",
    difficulty: "Oson",
    calories: 320,
    specialTouch: "Ugra bo'laklari an'anaviy usulda tayyorlangan."
  },
  {
    id: "7",
    name: "Pelmeni 'Sibir'",
    category: "Xamir ovqatlar",
    country: "Rossiya",
    description: "Yangi go'sht bilan to'ldirilgan an'anaviy pelmenilar.",
    ingredients: ["Xamir", "Yangi go'sht", "Ziravorlar"],
    instructions: ["Xamirni yoyish", "Ichiga go'shtni solish", "Qaynatib pishirish"],
    prepTime: "25 daqiqa",
    difficulty: "O'rta",
    calories: 280,
    specialTouch: "Pelmenilar ichida go'sht seli saqlanib qoladi."
  },
  {
    id: "8",
    name: "Somsa 'Tandir'",
    category: "Xamir ovqatlar",
    country: "O'zbekiston",
    description: "Haqiqiy tandirda pishirilgan, qarsildoq go'shtli somsa.",
    ingredients: ["Xamir", "Yangi go'sht", "Piyoz", "Zira"],
    instructions: ["Xamirni tayyorlash", "Ichiga masalliqni solish", "Haqiqiy tandirda pishirish"],
    prepTime: "20 daqiqa",
    difficulty: "O'rta",
    calories: 150,
    specialTouch: "Somsa tandir hidi bilan boyitilgan."
  },
  {
    id: "9",
    name: "Osh 'Tandir'",
    category: "Asosiy taomlar",
    country: "O'zbekiston",
    description: "Sara guruch va o'tin olovida tayyorlangan an'anaviy palov.",
    ingredients: ["Sara guruch", "Yangi qo'y go'shti", "Sariq sabzi", "Toza suv"],
    instructions: ["Guruchni damlash", "Go'shtni qozonda qovurish"],
    prepTime: "30 daqiqa",
    difficulty: "Qiyin",
    calories: 600,
    specialTouch: "Har bir guruch donasi alohida ajralib turadi."
  },
  {
    id: "10",
    name: "Miso Sho'rva 'Zen'",
    category: "Sho'rva",
    country: "Yaponiya",
    description: "Tinchlantiruvchi, an'anaviy yapon sho'rvasi.",
    ingredients: ["Miso pastasi", "Tofu", "Dengiz o'tlari", "Toza suv"],
    instructions: ["Suvni qaynatish", "Misoni eritish", "Tofuni kubik qilib solish"],
    prepTime: "5 daqiqa",
    difficulty: "Oson",
    calories: 80,
    specialTouch: "Sho'rva ichilganda o'zingizni xotirjam his qilasiz."
  },
  {
    id: "11",
    name: "Selyodka 'Pod Shuboy'",
    category: "Salatlar",
    country: "Rossiya",
    description: "An'anaviy qatlamli, juda mazali rus salati.",
    ingredients: ["Selyodka baliq", "Lavlagi", "Kartoshka", "Mayonez"],
    instructions: ["Qatlamlarni tartib bilan terish", "Sovutish"],
    prepTime: "15 daqiqa",
    difficulty: "O'rta",
    calories: 150,
    specialTouch: "Salat qatlamlari bir necha soat tursa yanada mazali bo'ladi."
  },
  {
    id: "12",
    name: "Roast Beef 'Royal'",
    category: "Asosiy taomlar",
    country: "Angliya",
    description: "Qirollik oilasi uslubida tayyorlangan, eng sara go'shtli taom.",
    ingredients: ["Premium go'sht", "Kartoshka", "Maxsus sous"],
    instructions: ["Go'shtni pechda pishirish", "Sous bilan bezash"],
    prepTime: "45 daqiqa",
    difficulty: "Qiyin",
    calories: 520,
    specialTouch: "Go'shtning yumshoqligi uni og'izda erishiga yordam beradi."
  },
  {
    id: "13",
    name: "Shashlik 'An'anaviy'",
    category: "Kaboblar",
    country: "O'zbekiston",
    description: "O'tin olovida pishirilgan, mislsiz darajada yumshoq shashlik.",
    ingredients: ["Qo'y go'shti", "Piyozli marinad", "Ziravorlar"],
    instructions: ["Go'shtni marinadlash", "Ko'mirda pishirish"],
    prepTime: "20 daqiqa",
    difficulty: "O'rta",
    calories: 380,
    specialTouch: "Go'sht bo'laklari o'tin hidi bilan boyitilgan."
  },
  {
    id: "14",
    name: "Tempura 'Classic'",
    category: "Qovurilgan taomlar",
    country: "Yaponiya",
    description: "Tez qovurilgan, yog'siz va qarsildoq tempura.",
    ingredients: ["Kreveta", "Un", "O'simlik yog'i"],
    instructions: ["Kravetani xamirga botirish", "Issiq yog'da qovurish"],
    prepTime: "5 daqiqa",
    difficulty: "Oson",
    calories: 120,
    specialTouch: "Tempura bo'laklari juda yengil va qarsildoq."
  },
  {
    id: "15",
    name: "Blini 'Classic'",
    category: "Shirinliklar",
    country: "Rossiya",
    description: "An'anaviy rus quymoqlari.",
    ingredients: ["Un", "Sut", "Asal"],
    instructions: ["Xamirni tayyorlash", "Tavada pishirish"],
    prepTime: "10 daqiqa",
    difficulty: "Oson",
    calories: 220,
    specialTouch: "Quymoqlar ustiga asal yoki murabbo surtib yeyish tavsiya etiladi."
  },
  {
    id: "16",
    name: "Beef Wellington 'Classic'",
    category: "Asosiy taomlar",
    country: "Angliya",
    description: "Pechda pishirilgan, xamir ichidagi mukammal go'sht.",
    ingredients: ["Go'sht", "Qatlamli xamir", "Qo'ziqorin pastasi", "Ziravorlar"],
    instructions: ["Go'shtni qovurish", "Xamirga o'rash", "Pechda qizartirish"],
    prepTime: "60 daqiqa",
    difficulty: "Qiyin",
    calories: 580,
    specialTouch: "Xamir qatlamlari go'sht seli bilan to'yingan bo'ladi."
  },
  {
    id: "17",
    name: "Lag'mon 'An'anaviy'",
    category: "Xamir ovqatlar",
    country: "O'zbekiston",
    description: "Qo'lda cho'zilgan, juda mazali lag'mon.",
    ingredients: ["Cho'ziluvchan un", "Yangi go'sht", "Sabzavotlar"],
    instructions: ["Xamirni cho'zish", "Sousni qozonda tayyorlash"],
    prepTime: "40 daqiqa",
    difficulty: "Qiyin",
    calories: 420,
    specialTouch: "Lag'mon xamiri qanchalik yupqa bo'lsa, shunchalik mazali bo'ladi."
  },
  {
    id: "18",
    name: "Yakitori 'Classic'",
    category: "Kaboblar",
    country: "Yaponiya",
    description: "An'anaviy usulda pishirilgan tovuq kaboblari.",
    ingredients: ["Tovuq", "Maxsus sous", "Zanjabil"],
    instructions: ["Tovuqni bo'laklash", "Sousda marinadlash", "Ko'mirda pishirish"],
    prepTime: "15 daqiqa",
    difficulty: "Oson",
    calories: 240,
    specialTouch: "Har bir bo'lak sous bilan to'yingan."
  },
  {
    id: "19",
    name: "Okroshka 'Classic'",
    category: "Sho'rva",
    country: "Rossiya",
    description: "Sovuq holda tortiladigan, muzli okroshka.",
    ingredients: ["Kvas", "Yangi sabzavotlar", "Kolbasa"],
    instructions: ["Masalliqlarni maydalash", "Kvas bilan aralashtirish"],
    prepTime: "10 daqiqa",
    difficulty: "Oson",
    calories: 110,
    specialTouch: "Sho'rva yoz kunlarida juda yaxshi chanqoq bosadi."
  },
  {
    id: "20",
    name: "Shepherd's Pie 'Classic'",
    category: "Asosiy taomlar",
    country: "Angliya",
    description: "Kartoshka pyuresi bilan tayyorlangan cho'pon pirogi.",
    ingredients: ["Kartoshka", "Yangi qiyma", "Pishloq"],
    instructions: ["Qiymani qovurish", "Kartoshkani pyure qilish", "Duxovkada pishirish"],
    prepTime: "35 daqiqa",
    difficulty: "O'rta",
    calories: 460,
    specialTouch: "Pirog ustidagi pishloq qarsildoq bo'lib pishadi."
  },
  {
    id: "21",
    name: "Ratatuy 'An'anaviy'",
    category: "Sabzavotli taomlar",
    country: "Fransiya",
    description: "Yupqa kesilgan sabzavotlardan iborat frantsuz klassikasi.",
    ingredients: ["Baqlajon", "Qovoqcha", "Pomidor", "Zaytun moyi"],
    instructions: ["Sabzavotlarni yupqa kesish", "Spiral shaklida terish", "Pechda pishirish"],
    prepTime: "25 daqiqa",
    difficulty: "O'rta",
    calories: 180,
    specialTouch: "Sabzavot bo'laklari bir xil qalinlikda kesilishi muhim."
  },
  {
    id: "22",
    name: "Croissant 'Classic'",
    category: "Pishiriqlar",
    country: "Fransiya",
    description: "Yengil va qatlamli an'anaviy frantsuz kruassani.",
    ingredients: ["Oliy navli un", "Sariyog'", "Shakar"],
    instructions: ["Xamirni ko'p qatlam qilib yoyish", "Pechda pishirish"],
    prepTime: "50 daqiqa",
    difficulty: "Qiyin",
    calories: 310,
    specialTouch: "Kruassan sirti qarsildoq, ichi esa yumshoq bo'lishi kerak."
  },
  {
    id: "23",
    name: "Quiche 'Classic'",
    category: "Pishiriqlar",
    country: "Fransiya",
    description: "An'anaviy mahsulotlardan tayyorlangan ochiq pirog.",
    ingredients: ["Tuxum", "Pishloq", "Ismaloq", "Vetchina"],
    instructions: ["Asosni pishirish", "Ichiga masalliqni solish", "Qayta pishirish"],
    prepTime: "30 daqiqa",
    difficulty: "O'rta",
    calories: 380,
    specialTouch: "Pirog issiq holda tortilsa yanada mazali bo'ladi."
  },
  {
    id: "24",
    name: "Bouillabaisse 'Classic'",
    category: "Sho'rva",
    country: "Fransiya",
    description: "Dengiz baliqlaridan tayyorlangan an'anaviy sho'rva.",
    ingredients: ["Baliqlar", "Zafaron", "Dengiz tuzi"],
    instructions: ["Baliqlarni qaynatish", "Zafaron qo'shish", "Filtrlash"],
    prepTime: "40 daqiqa",
    difficulty: "Qiyin",
    calories: 290,
    specialTouch: "Sho'rva boy ta'mga ega bo'lishi uchun bir necha turdagi baliq ishlatiladi."
  },
  {
    id: "25",
    name: "Coq au Vin 'Classic'",
    category: "Asosiy taomlar",
    country: "Fransiya",
    description: "Sharobda pishirilgan an'anaviy tovuq go'shti.",
    ingredients: ["Tovuq", "Qizil sharob", "Qo'ziqorin", "Piyoz"],
    instructions: ["Tovuqni sharobda marinadlash", "Past olovda uzoq pishirish"],
    prepTime: "5.5 soat",
    difficulty: "Qiyin",
    calories: 440,
    specialTouch: "Taom pishish jarayonida sharob hidi go'shtga chuqur singib ketadi."
  },
  {
    id: "26",
    name: "Kebab 'Tandir'",
    category: "Kaboblar",
    country: "O'zbekiston",
    description: "Tandirda pishirilgan, har bir bo'lagi mukammal qovurilgan kabob.",
    ingredients: ["Mol go'shti", "Maxsus marinad", "Ziravorlar"],
    instructions: ["Go'shtni tandirga terish", "Pishirish"],
    prepTime: "5 daqiqa",
    difficulty: "Oson",
    calories: 320,
    specialTouch: "Kabob tandirning o'ziga xos hidi bilan ajralib turadi."
  },
  {
    id: "27",
    name: "Manti 'An'anaviy'",
    category: "Xamir ovqatlar",
    country: "O'zbekiston",
    description: "Qo'lda tugilgan, juda yengil va mazali manti.",
    ingredients: ["Xamir", "Qiyma", "Piyoz", "Zira"],
    instructions: ["Mantini tugish", "Bug'da pishirish"],
    prepTime: "30 daqiqa",
    difficulty: "O'rta",
    calories: 210,
    specialTouch: "Manti xamiri yupqa bo'lishi uning sifatini belgilaydi."
  },
  {
    id: "28",
    name: "Karam Sho'rva 'Classic'",
    category: "Sho'rva",
    country: "O'zbekiston",
    description: "An'anaviy usulda maydalangan karamdan tayyorlangan sho'rva.",
    ingredients: ["Karam", "Go'sht", "Sabzi", "Toza suv"],
    instructions: ["Masalliqlarni maydalash", "Qaynatish"],
    prepTime: "15 daqiqa",
    difficulty: "Oson",
    calories: 180,
    specialTouch: "Sho'rva ichidagi karam bo'laklari yumshoq bo'lib pishadi."
  },
  {
    id: "29",
    name: "Sashimi 'Classic'",
    category: "Dengiz taomlari",
    country: "Yaponiya",
    description: "Tiniq baliq bo'laklaridan iborat an'anaviy sashimi.",
    ingredients: ["Baliq", "Vasabi", "Soya sousi"],
    instructions: ["Baliqni yupqa kesish", "Muz ustida tortish"],
    prepTime: "10 daqiqa",
    difficulty: "O'rta",
    calories: 140,
    specialTouch: "Baliqning yangiligi sashimining asosiy siri hisoblanadi."
  },
  {
    id: "30",
    name: "Udon 'Classic'",
    category: "Xamir ovqatlar",
    country: "Yaponiya",
    description: "An'anaviy usulda tayyorlangan yapon udoni.",
    ingredients: ["Udon ugrasi", "Bulyon", "Yangi piyoz"],
    instructions: ["Ugrani qaynoq suvga solish", "Pishirish"],
    prepTime: "1 daqiqa",
    difficulty: "Oson",
    calories: 290,
    specialTouch: "Udon pishishi bilan issiq holda tortiladi."
  },
  {
    id: "31",
    name: "Shchi 'An'anaviy'",
    category: "Sho'rva",
    country: "Rossiya",
    description: "An'anaviy usulda tayyorlangan rus shchisi.",
    ingredients: ["Karam", "Go'sht", "Toza suv", "Ziravorlar"],
    instructions: ["Karamni tayyorlash", "Sekin-asta pishirish"],
    prepTime: "20 daqiqa",
    difficulty: "O'rta",
    calories: 160,
    specialTouch: "Sho'rva ichidagi vitaminlar maksimal darajada saqlanadi."
  },
  {
    id: "32",
    name: "Vareniki 'Classic'",
    category: "Xamir ovqatlar",
    country: "Rossiya",
    description: "Yengil, tvorogli an'anaviy varenikilar.",
    ingredients: ["Xamir", "Tvorog", "Rezavorlar"],
    instructions: ["Varenikilarni tugish", "Bug'da pishirish"],
    prepTime: "15 daqiqa",
    difficulty: "Oson",
    calories: 230,
    specialTouch: "Varenikilar qaymoq bilan tortilsa yanada mazali bo'ladi."
  },
  {
    id: "33",
    name: "Eton Mess 'Classic'",
    category: "Desertlar",
    country: "Angliya",
    description: "Beze va qaymoqli an'anaviy ingliz deserti.",
    ingredients: ["Beze", "Qaymoq", "Yangi rezavorlar"],
    instructions: ["Bezena maydalash", "Qaymoq bilan aralashtirish", "Rezavorlar qo'shish"],
    prepTime: "10 daqiqa",
    difficulty: "Oson",
    calories: 340,
    specialTouch: "Desert ustidagi rezavorlar unga o'zgacha ko'rinish beradi."
  },
  {
    id: "34",
    name: "Bangers and Mash 'Classic'",
    category: "Asosiy taomlar",
    country: "Angliya",
    description: "An'anaviy sosiskalar va kartoshka pyuresi.",
    ingredients: ["Sosiska", "Kartoshka", "Maxsus sous"],
    instructions: ["Sosiskani qovurish", "Kartoshkani pyure qilish"],
    prepTime: "20 daqiqa",
    difficulty: "Oson",
    calories: 480,
    specialTouch: "Sosiskalar sirti qizarguncha qovurilishi kerak."
  },
  {
    id: "35",
    name: "Soufflé 'Classic'",
    category: "Desertlar",
    country: "Fransiya",
    description: "Pechda pishirilgan, yengil va havodor sufle.",
    ingredients: ["Tuxum oqi", "Shakar", "Vanil"],
    instructions: ["Tuxum oqini ko'pirtirish", "Vanil qo'shish", "Pechda pishirish"],
    prepTime: "25 daqiqa",
    difficulty: "Qiyin",
    calories: 190,
    specialTouch: "Sufle pechdan chiqqandan keyin darhol tortilishi kerak."
  },
  {
    id: "36",
    name: "Confit de Canard 'Classic'",
    category: "Asosiy taomlar",
    country: "Fransiya",
    description: "O'z yog'ida uzoq vaqt pishirilgan o'rdak go'shti.",
    ingredients: ["O'rdak oyog'i", "O'rdak yog'i", "Sarimsoq"],
    instructions: ["Go'shtni yog'ga botirish", "Pechda uzoq vaqt pishirish"],
    prepTime: "2 soat",
    difficulty: "Qiyin",
    calories: 550,
    specialTouch: "O'rdak terisi qarsildoq bo'lib pishishi kerak."
  },
  {
    id: "37",
    name: "Norin 'An'anaviy'",
    category: "Xamir ovqatlar",
    country: "O'zbekiston",
    description: "Yupqa kesilgan xamir va maydalangan go'shtdan iborat milliy taom.",
    ingredients: ["Xamir", "Ot go'shti", "Zira", "Piyoz"],
    instructions: ["Xamirni yupqa kesish", "Go'sht bilan aralashtirish"],
    prepTime: "30 daqiqa",
    difficulty: "O'rta",
    calories: 310,
    specialTouch: "Xamir bo'laklari bir xil va juda yupqa kesilishi kerak."
  },
  {
    id: "38",
    name: "Kabob 'Qo'ra'",
    category: "Kaboblar",
    country: "O'zbekiston",
    description: "Qo'rada, ko'mir olovida pishirilgan mazali kabob.",
    ingredients: ["Go'sht", "Maxsus marinad", "Ziravorlar"],
    instructions: ["Go'shtni sixga terish", "Ko'mirda pishirish"],
    prepTime: "10 daqiqa",
    difficulty: "O'rta",
    calories: 350,
    specialTouch: "Kabob ko'mirning xushbo'y hidi bilan boyitiladi."
  },
  {
    id: "39",
    name: "Tonkatsu 'Classic'",
    category: "Qovurilgan taomlar",
    country: "Yaponiya",
    description: "An'anaviy usulda qovurilgan, qarsildoq cho'chqa go'shti.",
    ingredients: ["Go'sht", "Panko", "O'simlik yog'i"],
    instructions: ["Go'shtni urish", "Pankoga botirish", "Qovurish"],
    prepTime: "20 daqiqa",
    difficulty: "O'rta",
    calories: 420,
    specialTouch: "Go'sht sirti oltin rangga kirguncha qovurilishi lozim."
  },
  {
    id: "40",
    name: "Matcha Cake 'Classic'",
    category: "Desertlar",
    country: "Yaponiya",
    description: "Matcha choyidan tayyorlangan, yashil rangli an'anaviy tort.",
    ingredients: ["Matcha", "Un", "Qaymoq", "Shakar"],
    instructions: ["Biskvit pishirish", "Krem bilan bezash"],
    prepTime: "45 daqiqa",
    difficulty: "Qiyin",
    calories: 280,
    specialTouch: "Matcha kukuni tortga o'zgacha rang va ta'm beradi."
  },
  {
    id: "41",
    name: "Kulebyaka 'An'anaviy'",
    category: "Xamir ovqatlar",
    country: "Rossiya",
    description: "An'anaviy usulda tayyorlangan, ko'p qatlamli baliqli pirog.",
    ingredients: ["Baliq", "Guruch", "Qo'ziqorin", "Xamir"],
    instructions: ["Qatlamlarni terish", "Xamirga o'rash", "Pechda pishirish"],
    prepTime: "50 daqiqa",
    difficulty: "Qiyin",
    calories: 410,
    specialTouch: "Pirog qatlamlari orasidagi muvozanat uning mazasini belgilaydi."
  },
  {
    id: "42",
    name: "Syrniki 'Classic'",
    category: "Shirinliklar",
    country: "Rossiya",
    description: "Tavada qovurilgan, ichi yumshoq va sirti qarsildoq syrnikilar.",
    ingredients: ["Tvorog", "Un", "Tuxum", "Asal"],
    instructions: ["Tvorogni aralashtirish", "Dumaloq shakl berish", "Qovurish"],
    prepTime: "15 daqiqa",
    difficulty: "Oson",
    calories: 260,
    specialTouch: "Syrnikilar issiq holda, smetana bilan tortilsa juda mazali bo'ladi."
  },
  {
    id: "43",
    name: "Trifle 'Classic'",
    category: "Desertlar",
    country: "Angliya",
    description: "Qatlamli, mevali va qaymoqli an'anaviy ingliz deserti.",
    ingredients: ["Biskvit", "Kustard", "Jele", "Qaymoq"],
    instructions: ["Qatlamlarni shisha idishga terish", "Sovutish"],
    prepTime: "20 daqiqa",
    difficulty: "O'rta",
    calories: 390,
    specialTouch: "Desert ichidagi mevalar unga tazelik bag'ishlaydi."
  },
  {
    id: "44",
    name: "Scotch Egg 'Classic'",
    category: "Qovurilgan taomlar",
    country: "Angliya",
    description: "Go'sht bilan o'ralgan va qovurilgan an'anaviy tuxum.",
    ingredients: ["Tuxum", "Qiyma", "Non talqoni", "Ziravorlar"],
    instructions: ["Tuxumni qaynatish", "Qiyma bilan o'rash", "Qovurish"],
    prepTime: "25 daqiqa",
    difficulty: "O'rta",
    calories: 320,
    specialTouch: "Tuxum sarig'i biroz suyuq holda qolsa yanada yaxshi."
  },
  {
    id: "45",
    name: "Macarons 'Classic'",
    category: "Desertlar",
    country: "Fransiya",
    description: "Bodom unidan tayyorlangan, rang-barang frantsuz shirinligi.",
    ingredients: ["Bodom uni", "Shakar upasi", "Tuxum oqi", "Mevali essensiya"],
    instructions: ["Xamirni tayyorlash", "Pishirish", "Krem bilan birlashtirish"],
    prepTime: "60 daqiqa",
    difficulty: "Qiyin",
    calories: 110,
    specialTouch: "Har bir rangdagi makaron o'ziga xos meva ta'mini beradi."
  },
  {
    id: "46",
    name: "Escargot 'Classic'",
    category: "Gazaklar",
    country: "Fransiya",
    description: "Sarimsoqli sariyog'da pishirilgan an'anaviy shilliqqurtlar.",
    ingredients: ["Shilliqqurt", "Sariyog'", "Sarimsoq", "Ko'katlar"],
    instructions: ["Shilliqqurtlarni tozalash", "Sariyog' bilan pishirish"],
    prepTime: "30 daqiqa",
    difficulty: "O'rta",
    calories: 220,
    specialTouch: "Taom maxsus chig'anoqlarda tortilishi shart."
  },
  {
    id: "47",
    name: "Chuchvara 'An'anaviy'",
    category: "Xamir ovqatlar",
    country: "O'zbekiston",
    description: "Kichik qilib tugilgan, mazali bulyonli chuchvaralar.",
    ingredients: ["Xamir", "Qiyma", "Murch", "Sutli bulyon"],
    instructions: ["Chuchvaralarni tugish", "Bulyonda pishirish"],
    prepTime: "40 daqiqa",
    difficulty: "Qiyin",
    calories: 280,
    specialTouch: "Chuchvaralar qanchalik kichik bo'lsa, shunchalik mahoratli hisoblanadi."
  },
  {
    id: "48",
    name: "Dimlama 'An'anaviy'",
    category: "Asosiy taomlar",
    country: "O'zbekiston",
    description: "Qozonda uzoq vaqt dimlangan sabzavotli go'sht.",
    ingredients: ["Go'sht", "Kartoshka", "Karam", "Qalampir"],
    instructions: ["Masalliqlarni qozonga terish", "Past olovda 3 soat dimlash"],
    prepTime: "3.5 soat",
    difficulty: "O'rta",
    calories: 450,
    specialTouch: "Taom o'z suvida pishishi uning asosiy siri."
  },
  {
    id: "49",
    name: "Nikujaga 'Classic'",
    category: "Asosiy taomlar",
    country: "Yaponiya",
    description: "An'anaviy usulda tayyorlangan go'sht va kartoshkali dimlama.",
    ingredients: ["Go'sht", "Kartoshka", "Soya sousi", "Mirin"],
    instructions: ["Masalliqlarni qovurish", "Sousda dimlash"],
    prepTime: "30 daqiqa",
    difficulty: "Oson",
    calories: 360,
    specialTouch: "Kartoshka bo'laklari butun holda pishishi kerak."
  },
  {
    id: "50",
    name: "Okonomiyaki 'Classic'",
    category: "Asosiy taomlar",
    country: "Yaponiya",
    description: "Tavada pishiriladigan, mashhur yapon pitsasi.",
    ingredients: ["Karam", "Un", "Tuxum", "Dengiz mahsulotlari", "Maxsus sous"],
    instructions: ["Xamirni tayyorlash", "Tavada qovurish", "Sous bilan bezash"],
    prepTime: "20 daqiqa",
    difficulty: "O'rta",
    calories: 440,
    specialTouch: "Taom ustiga sepiladigan baliq qirindilari unga o'zgacha maza beradi."
  },
  {
    id: "51",
    name: "Qozon kabob",
    category: "Asosiy taomlar",
    country: "O'zbekiston",
    description: "Qozonda qovurilgan go'sht va kartoshkadan iborat to'yimli taom.",
    ingredients: ["Qo'y go'shti", "Kartoshka", "Zira", "Kashnich urug'i"],
    instructions: ["Go'shtni qizigan yog'da qizartirib qovurish", "Kartoshkalarni butunligicha qovurish", "Past olovda 1 soat dimlash"],
    prepTime: "1.5 soat",
    difficulty: "O'rta",
    calories: 550,
    specialTouch: "Kartoshkalar go'sht seli bilan to'yinib, juda mazali bo'ladi."
  },
  {
    id: "52",
    name: "Mastava",
    category: "Sho'rva",
    country: "O'zbekiston",
    description: "Guruch va sabzavotlardan tayyorlangan, quvvatbaxsh milliy sho'rva.",
    ingredients: ["Guruch", "Go'sht", "Sabzi", "Piyoz", "Qatiq"],
    instructions: ["Go'sht va sabzavotlarni qovurish", "Suv quyib qaynatish", "Guruch qo'shib pishirish"],
    prepTime: "45 daqiqa",
    difficulty: "Oson",
    calories: 320,
    specialTouch: "Mastava qatiq va rayhon bilan tortilsa juda mazali bo'ladi."
  },
  {
    id: "53",
    name: "Achchiq-chuchuk",
    category: "Salatlar",
    country: "O'zbekiston",
    description: "Pomidor, piyoz va achchiq qalampirdan tayyorlangan an'anaviy o'zbek salati.",
    ingredients: ["Pomidor", "Piyoz", "Achchiq qalampir", "Rayhon"],
    instructions: ["Pomidor va piyozni juda yupqa to'g'rash", "Murch va tuz sepish", "Yaxshilab aralashtirish"],
    prepTime: "10 daqiqa",
    difficulty: "Oson",
    calories: 45,
    specialTouch: "Palov bilan birga tortilishi shart."
  },
  {
    id: "54",
    name: "Olivye 'Classic'",
    category: "Salatlar",
    country: "Rossiya",
    description: "Bayram dasturxonlarining ko'rki bo'lgan an'anaviy rus salati.",
    ingredients: ["Qaynatilgan kartoshka", "Sabzi", "Tuxum", "Tuzlangan bodring", "Yashil no'xat", "Mayonez"],
    instructions: ["Barcha masalliqlarni kubik shaklida to'g'rash", "Mayonez bilan aralashtirish"],
    prepTime: "20 daqiqa",
    difficulty: "O'rta",
    calories: 220,
    specialTouch: "Masalliqlar bir xil kattalikda to'g'ralishi muhim."
  },
  {
    id: "55",
    name: "Grek salati",
    category: "Salatlar",
    country: "Gretsiya",
    description: "Yangi sabzavotlar va Feta pishlog'idan tayyorlangan vitaminli salat.",
    ingredients: ["Bodring", "Pomidor", "Feta pishlog'i", "Zaytun", "Zaytun moyi"],
    instructions: ["Sabzavotlarni yirik to'g'rash", "Pishloq va zaytun qo'shish", "Zaytun moyi quyish"],
    prepTime: "15 daqiqa",
    difficulty: "Oson",
    calories: 160,
    specialTouch: "Feta pishlog'i salatga o'zgacha sho'rroq ta'm beradi."
  },
  {
    id: "56",
    name: "Sezar salati",
    category: "Salatlar",
    country: "Italiya",
    description: "Tovuq go'shti va maxsus sous bilan tayyorlangan mashhur salat.",
    ingredients: ["Tovuq filesi", "Aysberg salat bargi", "Suxariklar", "Parmezan pishlog'i", "Sezar sousi"],
    instructions: ["Tovuqni qovurish", "Salat barglarini qo'lda bo'lish", "Sous va pishloq bilan aralashtirish"],
    prepTime: "25 daqiqa",
    difficulty: "O'rta",
    calories: 310,
    specialTouch: "Suxariklar oxirida qo'shilsa, ular qarsildoq bo'lib turadi."
  },
  {
    id: "57",
    name: "Fish & Chips 'Classic'",
    category: "Qovurilgan taomlar",
    country: "Angliya",
    description: "Qovurilgan baliq va kartoshka fri.",
    ingredients: ["Baliq", "Kartoshka", "Un"],
    instructions: ["Baliqni qovurish", "Kartoshkani pishirish"],
    prepTime: "15 daqiqa",
    difficulty: "Oson",
    calories: 430,
    specialTouch: "Baliq klyari qarsildoq bo'lishi kerak."
  },
  {
    id: "58",
    name: "Steyk 'Ribay'",
    category: "Asosiy taomlar",
    country: "AQSH",
    description: "Eng sara mol go'shtidan tayyorlangan, suvli va mazali steyk.",
    ingredients: ["Ribay go'shti", "Sariyog'", "Rozmarin", "Sarimsoq"],
    instructions: ["Go'shtni xona haroratiga keltirish", "Tavada har bir tomonini 3-4 daqiqa qovurish", "Sariyog' va rozmarin bilan boyitish"],
    prepTime: "20 daqiqa",
    difficulty: "O'rta",
    calories: 680,
    specialTouch: "Steykni pishirgandan keyin 5 daqiqa 'dam' berish muhim."
  },
  {
    id: "59",
    name: "Bahor salati",
    category: "Salatlar",
    country: "O'zbekiston",
    description: "Yangi ko'katlar va bodringdan tayyorlangan bahoriy salat.",
    ingredients: ["Bodring", "Rediska", "Ko'k piyoz", "Kashnich", "Qatiq yoki smetana"],
    instructions: ["Sabzavotlarni to'g'rash", "Ko'katlarni maydalash", "Qatiq bilan aralashtirish"],
    prepTime: "10 daqiqa",
    difficulty: "Oson",
    calories: 60,
    specialTouch: "Yangi uzilgan ko'katlar salatga o'zgacha tarovat beradi."
  },
  {
    id: "60",
    name: "Yaponcha bodring salati",
    category: "Salatlar",
    country: "Yaponiya",
    description: "Sirkali sous bilan tayyorlangan yengil yapon salati.",
    ingredients: ["Bodring", "Guruch sirkasi", "Kunjut", "Shakar"],
    instructions: ["Bodringni yupqa parrak qilish", "Sirka va shakarli sous tayyorlash", "Kunjut sepish"],
    prepTime: "10 daqiqa",
    difficulty: "Oson",
    calories: 40,
    specialTouch: "Bodringlar sousni yaxshi shimishi uchun biroz vaqt qolishi kerak."
  }
];
